### ISSUE TITLE
Colaborar?

### ISSUE THREAD

**Issue by mgaitan** [dedio/bora-scraper#1]
Hola @dedio, estoy interesado en desarrollar una idea para extraer y semantizar e hipervincular data de boletines oficiales de nación y provincia, probablemente cruzado con otros datasets como IGJ. 
Por ahora está en fase "idea inacabada" y esto relevando qué hay hecho. Yo codeo principalmente python asi que si esto está andando me vendria bien. 

Te interesaria aunar esfuerzos de alguna manera? aunque sea discutir qué sería prioritario hacer una "plataforma"? 

https://github.com/mgaitan/wikibora/issues/1

**Comment by dedio** [comment]
Martín:
Me parece una idea interesante.  Con respecto a la plataforma creo que Django es lo más conveniente.  Acá podés encontrar https://github.com/dedio/django_scraping_template un ejemplo de como utilizarla con scrapers.   Este template permite gestionar cualquier tipo de spider.  Fijate además que hay también un scraper del boletín oficial de la Ciudad de Buenos Aires https://github.com/dedio/bocaba_scraper.  ¿Cual es tu idea de trabajo, que servicio ofrecerías?

**Comment by mgaitan** [comment]
@dedio las posibilidades son varias. Poder mantener una base de sociedades (como libreborme.net), historial de funcionarios, graficos de deuda, etc. https://htmlpreview.github.io/?https://raw.githubusercontent.com/datoslibres/boletinoficial/master/bonos.html

Por otro lado, el hecho de que los textos estén hipervinculados lo hace más navegable.

**Comment by dedio** [comment]
Es una muy buena idea.  El scraper bora se puede tunear para que levante las publicaciones dentro de un rango de dias determinado.  En el caso de bocada hay una API que tendría que revisar para levantar un lapso de tiempo.  Esto permitiría tener ya una buena base con que arrancar.  Digamos el último añó por ejemplo (en la medida que se pueda) y hacer pruebas con la semantización y la hipervinculación.  Por otro lado con respecto al de la provincia de Buenos Aires, tendría que verlo.  ¿qué te parece hasta aquí?

**Comment by dedio** [comment]
Es una muy buena idea.  El scraper bora se puede tunear para que levante las publicaciones dentro de un rango de dias determinado.  En el caso de bocada hay una API que tendría que revisar para levantar un lapso de tiempo.  Esto permitiría tener ya una buena base con que arrancar.  Digamos el último añó por ejemplo (en la medida que se pueda) y hacer pruebas con la semantización y la hipervinculación.  Por otro lado con respecto al de la provincia de Buenos Aires, tendría que verlo.  ¿qué te parece hasta aquí?

**Comment by dedio** [comment]
Es una muy buena idea.  El scraper bora se puede tunear para que levante las publicaciones dentro de un rango de días determinado.  En el caso de bocada hay una API que tendría que revisar para levantar un lapso de tiempo.  Esto permitiría tener ya una buena base con que arrancar.  Digamos el último año por ejemplo (en la medida que se pueda) y hacer pruebas con la semantización y la hipervinculación.  Por otro lado con respecto al de la provincia de Buenos Aires, tendría que verlo.  ¿qué te parece hasta aquí?
